import type { NextPage, GetStaticProps } from 'next'
import Head from 'next/head'

import Hero from '../components/Hero'
import Featured from '../components/Featured'

import { getFeaturedBlogs } from '../lib/fetchPosts'
import { Blog } from '../types/blog-types'

interface Props {
  blogs: Blog[]
}

const Home: NextPage<Props> = ({ blogs }) => {
  return (
    <>
      <Head>
        <title>El Blog el motawade3 beta3y</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.png' />
      </Head>
      <Hero />
      <Featured blogs={blogs} />
    </>
  )
}

export const getStaticProps: GetStaticProps = () => {
  const featuredBlogs = getFeaturedBlogs()

  return {
    props: {
      blogs: featuredBlogs,
    },
  }
}

export default Home
